name: "Deployment Action"
description: "Creates a GitHub Deployment"
author: "chrnorm"
branding:
  icon: arrow-up
  color: black
inputs:
  token:
    description: "Github repository token"
    required: true
  url:
    description: "Deployment location"
    required: true
  description:
    description: "Descriptive message about the deployment"
    required: false
  environment:
    description: "The name of the environment for the deployment"
    default: "development"
    required: false
outputs:
  deployment_id:
    description: "The ID of the created deployment"
runs:
  using: "node12"
  main: "main/index.js"
  post: post/index.js
